# Nama alur kerja yang akan tampil di tab Actions GitHub
name: Deploy Laravel to Shared Hosting

# Pemicu: Jalankan alur kerja ini setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Menggunakan server virtual Ubuntu terbaru dari GitHub untuk menjalankan proses
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengunduh kode dari repositori Anda ke server virtual
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Menyiapkan environment PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Sesuaikan jika versi PHP Anda berbeda

      # Langkah 3: Menyiapkan environment Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Sesuaikan jika versi Node.js Anda berbeda

      # Langkah 4: Menginstall dependensi PHP dengan Composer
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # Langkah 5: Menginstall dependensi JS (npm) dan build aset CSS/JS
      - name: Install NPM dependencies and build
        run: |
          npm install
          npm run build

      # Langkah 6: Mengirim file yang sudah siap ke server shared hosting Anda
      - name: Deploy application files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }} # Menggunakan port kustom Anda
          script: |
            # SINKRONISASI 1: Menyalin file inti Laravel (tanpa folder public)
            rsync -avz --delete --exclude 'public' --exclude '.git' ./ /home/pokdarw4/pokdarwis-landing-page/
            
            # SINKRONISASI 2: Menyalin HANYA ISI folder public ke public_html
            rsync -avz --delete ./public/ /home/pokdarw4/public_html/
            
            # Pindah ke direktori inti aplikasi di server untuk menjalankan perintah
            cd /home/pokdarw4/pokdarwis-landing-page
            
            # Menjalankan perintah akhir di server
            echo "Running post-deploy commands..."
            php artisan down
            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize
            php artisan up
            echo "Deployment finished successfully!"
